export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  OPERATIONS_MANAGER = 'OPERATIONS_MANAGER',
  PRODUCT_MANAGER = 'PRODUCT_MANAGER',
  DELIVERY_MANAGER = 'DELIVERY_MANAGER',
  FINANCE_MANAGER = 'FINANCE_MANAGER',
  CUSTOMER_SUPPORT = 'CUSTOMER_SUPPORT',
  MARKETING_MANAGER = 'MARKETING_MANAGER',
  REPORT_VIEWER = 'REPORT_VIEWER',
}

export enum Permission {
  CUSTOMER_VIEW = 'customer.view',
  CUSTOMER_EDIT = 'customer.edit',
  PRODUCT_CREATE = 'product.create',
  PRODUCT_EDIT = 'product.edit',
  ORDER_CANCEL = 'order.cancel',
  SUBSCRIPTION_MANAGE = 'subscription.manage',
  DELIVERY_ASSIGN = 'delivery.assign',
  PAYMENT_REFUND = 'payment.refund',
  BOTTLE_ADJUST = 'bottle.adjust',
  REPORT_EXPORT = 'report.export',
  SETTINGS_MANAGE = 'settings.manage',
}

export enum OrderType {
  ONE_TIME = 'ONE_TIME',
  SUBSCRIPTION = 'SUBSCRIPTION',
  ADMIN_CREATED = 'ADMIN_CREATED',
  REPLACEMENT = 'REPLACEMENT',
}

export enum OrderStatus {
  DRAFT = 'DRAFT',
  PLACED = 'PLACED',
  CONFIRMED = 'CONFIRMED',
  SCHEDULED = 'SCHEDULED',
  ASSIGNED = 'ASSIGNED',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  DELIVERED = 'DELIVERED',
  FAILED = 'FAILED',
  SKIPPED = 'SKIPPED',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
}

export enum SubscriptionFrequency {
  DAILY = 'DAILY',
  ALTERNATE_DAYS = 'ALTERNATE_DAYS',
  WEEKLY = 'WEEKLY',
  MONTHLY = 'MONTHLY',
  CUSTOM = 'CUSTOM',
}

export enum SubscriptionStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  PAYMENT_PENDING = 'PAYMENT_PENDING',
}

export enum PaymentStatus {
  CREATED = 'CREATED',
  PENDING = 'PENDING',
  AUTHORIZED = 'AUTHORIZED',
  PAID = 'PAID',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
  PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED',
  CANCELLED = 'CANCELLED',
}

export enum PaymentMethod {
  WALLET = 'WALLET',
  RAZORPAY = 'RAZORPAY',
  UPI = 'UPI',
  CARD = 'CARD',
  NET_BANKING = 'NET_BANKING',
  CASH = 'CASH',
  PARTIAL_WALLET_ONLINE = 'PARTIAL_WALLET_ONLINE',
  POSTPAID = 'POSTPAID',
}

export enum WalletTransactionType {
  RECHARGE = 'RECHARGE',
  ORDER_PAYMENT = 'ORDER_PAYMENT',
  REFUND = 'REFUND',
  REFERRAL_REWARD = 'REFERRAL_REWARD',
  PROMOTIONAL_CREDIT = 'PROMOTIONAL_CREDIT',
  MANUAL_ADJUSTMENT = 'MANUAL_ADJUSTMENT',
  POSTPAID_SETTLEMENT = 'POSTPAID_SETTLEMENT',
  REVERSAL = 'REVERSAL',
}

export enum BottleTransactionType {
  ISSUED = 'ISSUED',
  COLLECTED = 'COLLECTED',
  BROKEN = 'BROKEN',
  LOST = 'LOST',
  ADJUSTED = 'ADJUSTED',
  DEPOSIT_CHARGED = 'DEPOSIT_CHARGED',
  DEPOSIT_REFUNDED = 'DEPOSIT_REFUNDED',
}

export enum DeliveryStatus {
  PENDING = 'PENDING',
  ASSIGNED = 'ASSIGNED',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  DELIVERED = 'DELIVERED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

export enum DeliveryFailureReason {
  CUSTOMER_UNAVAILABLE = 'CUSTOMER_UNAVAILABLE',
  WRONG_ADDRESS = 'WRONG_ADDRESS',
  CUSTOMER_REFUSED = 'CUSTOMER_REFUSED',
  PAYMENT_NOT_AVAILABLE = 'PAYMENT_NOT_AVAILABLE',
  PRODUCT_ISSUE = 'PRODUCT_ISSUE',
  ACCESS_RESTRICTED = 'ACCESS_RESTRICTED',
  OTHER = 'OTHER',
}

export enum AddressType {
  HOME = 'HOME',
  WORK = 'WORK',
  OTHER = 'OTHER',
}

export enum ProductBadge {
  ORGANIC = 'ORGANIC',
  FARM_FRESH = 'FARM_FRESH',
  NO_PRESERVATIVES = 'NO_PRESERVATIVES',
  A2 = 'A2',
  BEST_SELLER = 'BEST_SELLER',
}

export enum NotificationType {
  ORDER_PLACED = 'ORDER_PLACED',
  PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  DELIVERY_OUT = 'DELIVERY_OUT',
  DELIVERY_COMPLETED = 'DELIVERY_COMPLETED',
  DELIVERY_FAILED = 'DELIVERY_FAILED',
  SUBSCRIPTION_UPCOMING = 'SUBSCRIPTION_UPCOMING',
  SUBSCRIPTION_PAUSED = 'SUBSCRIPTION_PAUSED',
  LOW_WALLET = 'LOW_WALLET',
  BOTTLE_REMINDER = 'BOTTLE_REMINDER',
  OFFER = 'OFFER',
  REFERRAL_REWARD = 'REFERRAL_REWARD',
  ADMIN_ANNOUNCEMENT = 'ADMIN_ANNOUNCEMENT',
}

export enum TicketStatus {
  OPEN = 'OPEN',
  IN_PROGRESS = 'IN_PROGRESS',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED',
}

export enum TicketCategory {
  ORDER_ISSUE = 'ORDER_ISSUE',
  DELIVERY_ISSUE = 'DELIVERY_ISSUE',
  PAYMENT_ISSUE = 'PAYMENT_ISSUE',
  PRODUCT_QUALITY = 'PRODUCT_QUALITY',
  SUBSCRIPTION_ISSUE = 'SUBSCRIPTION_ISSUE',
  BOTTLE_ISSUE = 'BOTTLE_ISSUE',
  ACCOUNT_ISSUE = 'ACCOUNT_ISSUE',
  OTHER = 'OTHER',
}

export enum AttendanceStatus {
  CHECKED_IN = 'CHECKED_IN',
  CHECKED_OUT = 'CHECKED_OUT',
}

export enum RouteStatus {
  PLANNED = 'PLANNED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}
